name: "Terraform Manual State Fix"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  state-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.OIDC_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Init
        run: terraform init

      - name: Remove Stuck Role from State
        run: |
          terraform state rm aws_iam_role.create_lambda_role || true
          terraform state rm aws_iam_role.retrieve_lambda_role || true